### ISSUE TITLE
Adding new diagnostic to html files

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fdiag#3]
Hey Nikolay, 
I added a diagnostic where the ice area, extent and volume for March, September and for SH & NH are added in just one plot each. The plots look fine, e.g.
![image](https://user-images.githubusercontent.com/25483665/133457132-59c2a4a5-ab50-4f7d-a6f6-ea4e9ae9788d.png)
but adding them to the html file did not quite work:
```
fdiag ice_vol_test.yml 
/p/project/chhb19/jstreffi/software/fdiag/fdiag/templates
The names of runs to be processed are:['PICT']
Data on previous runs exist in ./results/ice_vol_test/ice_vol_test.json, 

they will be used to generate output for diagnostics you do not run this time.
!!! Performing ice_integrals_combined_nocomparison !!!
Executing:  31%|██████████████████████████████████████████████████▋                                                                                                               | 5/16 [00:03<00:05,  2.11cell/s]sh: convert: command not found
mv: cannot stat './results/ice_vol_test/figures/ice_vol_test_ice_integrals_combined_nocomparison_icearea_combined.png_trimmed.png': No such file or directory
Executing:  50%|█████████████████████████████████████████████████████████████████████████████████                                                                                 | 8/16 [00:07<00:07,  1.10cell/s]sh: convert: command not found
mv: cannot stat './results/ice_vol_test/figures/ice_vol_test_ice_integrals_combined_nocomparison_iceext_combined.png_trimmed.png': No such file or directory
Executing:  75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 12/16 [00:14<00:05,  1.44s/cell]sh: convert: command not found
mv: cannot stat './results/ice_vol_test/figures/ice_vol_test_ice_integrals_combined_nocomparison_icevol_combined.png_trimmed.png': No such file or directory
Executing: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:15<00:00,  1.06cell/s]
```

In particular this part: `_combined.png_trimmed.png` seems wrong. Maybe you can have a quick look at my work here: https://github.com/FESOM/fdiag/tree/combined_ice_integrals I'm guessing this is easy to fix.

p.s.
I tired to have the feature such that there is one color per experiment and different linestyles per season and hemisphere, but I found the result much less clear than using different colors for each season and hemisphere. Therefore I deviate fromt he default blue/orange color scheme.

**Comment by koldunovn** [comment]
@JanStreffing This looks really nice, thanks a lot for adding it!

Looks like the failure is at the level of the notebook, and in your output notebook I found the warning:
```sh
sh: convert: command not found
mv: cannot stat './results/ice_vol_test/figures/ice_vol_test_ice_integrals_combined_nocomparison_icevol_combined.png_trimmed.png': No such file or directory
```

I hope:

```
module load GCCcore/.10.3.0
module load ImageMagick/7.0.10-25
```
will fix the issue. Relying on ImageMagick for conversion is not the best idea, although I thought it is installed everywhere, but I am wrong :)) Probably we have to change it to pythonic way of trimming.

**Comment by JanStreffing** [comment]
I found and loaded `ImageMagick/7.0.10-25`, but not the `GCCcore/.10.3.0:`
```
module spider GCCcore
Lmod has detected the following error:  Unable to find: "GCCcore".
```

I tried like this, since I do have a gcc compiler by default, without loading a module. I had to make one more small change to the path in drivers.py, then it worked.
